const $=id=>document.getElementById(id);
const names=['One sample at a time','One flight/no optimization','TG-1 optimized'];
const copies=['Separate trips for each detected sample','One sampling flight along the full survey route','One flight connecting the detected locations'];
let selection=null,mission=null,seed=17,stage='scan';
const costIds=['manualCrew','manualWage','manualChemical','manualCapacity','uasCrew','uasWage','uasChemical','uasCapacity','chemical','lossPerAcre'];
const states='Alabama|Alaska|Arizona|Arkansas|California|Colorado|Connecticut|Delaware|Florida|Georgia|Hawaii|Idaho|Illinois|Indiana|Iowa|Kansas|Kentucky|Louisiana|Maine|Maryland|Massachusetts|Michigan|Minnesota|Mississippi|Missouri|Montana|Nebraska|Nevada|New Hampshire|New Jersey|New Mexico|New York|North Carolina|North Dakota|Ohio|Oklahoma|Oregon|Pennsylvania|Rhode Island|South Carolina|South Dakota|Tennessee|Texas|Utah|Vermont|Virginia|Washington|West Virginia|Wisconsin|Wyoming'.split('|');
$('state').innerHTML=states.map(state=>`<option value="${state}">${state}${TG1_LOSS_DATA.states[state]?'':' · enter rate'}</option>`).join('');$('state').value='Maryland';
function lossNote(){const d=TG1_LOSS_DATA.states[$('state').value],v=$('lossPerAcre').valueAsNumber;$('lossnote').textContent=d?(v===d.lossPerAcre?`${d.year} state estimate · editable`:`Custom rate · ${d.year} state estimate: $${f(d.lossPerAcre)}/acre`):(Number.isFinite(v)?'Custom rate · no published state estimate in this dataset.':'No published state estimate in this dataset. Enter your expected loss per acre.');}
const f=n=>n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const money=n=>n===null?'—':n.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});
const row=(a,b)=>`<tr><td>${a}</td><td>${b}</td></tr>`;
const active=()=>selection===null?null:mission?.scenarios[selection];
names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.className='routecard';b.setAttribute('role','radio');b.setAttribute('aria-checked','false');b.dataset.route=i;b.innerHTML=`<div class="routehead"><span class="radio" aria-hidden="true"></span>${name}</div><p class="routecopy">${copies[i]}</p><div class="routemetrics" id="metrics${i}" hidden></div>`;b.onclick=()=>{if(!mission)return;selection=i;renderResults();if(stage!=='scan')startSampling();else $('flightstatus').textContent='Scanning first; sampling will follow';};b.onkeydown=e=>{if(['ArrowDown','ArrowRight','ArrowUp','ArrowLeft'].includes(e.key)){e.preventDefault();const j=(i+(['ArrowDown','ArrowRight'].includes(e.key)?1:2))%3;const next=document.querySelector(`[data-route="${j}"]`);next.click();next.focus();}};$('routes').append(b);});
function startSampling(){if(selection===null||!mission)return;stage='sample';$('visualtitle').textContent=names[selection];$('flightstatus').textContent='Sampling detected locations';FieldView.render({mission,phase:'sample',selection,complete:()=>{$('flightstatus').textContent='Sampling complete · returned to ground control';stage='complete';renderResults();}});}
function startScanning(){stage='scan';$('visualtitle').textContent='Automatic scanning';$('flightstatus').textContent='Finding damaged locations';FieldView.render({mission,phase:'scan',complete:()=>{stage='detected';if(selection!==null)startSampling();else{$('visualtitle').textContent='Scanning complete';$('flightstatus').textContent='Returned to ground control · choose a sampling strategy';FieldView.render({mission,phase:'idle'});}}});}
function inputs(){return{area:$('area').valueAsNumber,damage:$('damage').valueAsNumber,distance:$('distance').valueAsNumber,speed:$('speed').valueAsNumber,distribution:$('distribution').value,state:$('state').value,...Object.fromEntries(costIds.map(id=>[id,id==='lossPerAcre'&&$(id).value===''?null:$(id).valueAsNumber])),seed};}
function update(){selection=null;$('reshuffle').hidden=$('distribution').value==='Scattered';document.querySelector('.inputactions span').hidden=$('reshuffle').hidden;try{mission=TG1.plan(inputs());$('error').hidden=true;$('costerror').hidden=true;['area','damage','distance','speed'].forEach(id=>$(id).removeAttribute('aria-invalid'));}catch(e){mission=null;$('error').textContent=e.message;$('error').hidden=false;renderResults();$('visualtitle').textContent='Your field';$('flightstatus').textContent='Enter valid mission inputs';FieldView.render({mission:null});return;}$('reshuffle').disabled=mission.count===0||mission.count===mission.cells.length;renderResults();startScanning();}
['area','damage','distance','speed'].forEach(id=>$(id).addEventListener('input',update));['distribution'].forEach(id=>$(id).addEventListener('change',update));function updateCosts(){lossNote();try{const wasValid=!!mission,next=TG1.plan(inputs());$('costerror').hidden=true;mission=next;if(!wasValid){update();return;}renderResults();}catch(e){$('costerror').textContent=e.message;$('costerror').hidden=false;$('comparison').hidden=true;$('graphs').hidden=true;$('evaluation').hidden=true;$('feedbacksection').hidden=true;document.querySelectorAll('.routecard').forEach(b=>b.disabled=true);}}
$('reshuffle').onclick=()=>{const previous=mission?.damageIds.slice().sort((a,b)=>a-b).join(',');for(let attempt=0;attempt<64;attempt++){seed=(seed+104729)>>>0;const candidate=TG1.plan(inputs());if(candidate.damageIds.slice().sort((a,b)=>a-b).join(',')!==previous)break;}update();};$('motiontoggle').onclick=()=>FieldView.toggle();
costIds.forEach(id=>$(id).addEventListener('input',updateCosts));$('state').addEventListener('change',()=>{$('lossPerAcre').value=TG1_LOSS_DATA.states[$('state').value]?.lossPerAcre??'';updateCosts();});
function renderResults(){document.querySelectorAll('.routecard').forEach((b,i)=>{b.disabled=!mission;b.setAttribute('aria-checked',String(selection===i));const m=$('metrics'+i);m.hidden=selection!==i;if(mission){const s=mission.scenarios[i];m.innerHTML=`<div><span class="meta">Scanning + sampling</span><strong>${f(s.operation)} <small>min</small></strong></div><div><span class="meta">Total distance</span><strong>${f(s.total)} <small>mi</small></strong></div>`;}});const s=active();$('comparison').hidden=!s;$('graphs').hidden=!s;$('evaluation').hidden=!s;$('feedbacksection').hidden=!s;if(!s)return;renderEvaluation(s);const methods=[mission.manual,mission.uas,s.economics];$('comparisontable').innerHTML=`<thead><tr><th scope="col">Measure</th>${methods.map(m=>`<th scope="col">${m.name==='Conventional UAS'?'<span class="conventional">Conventional </span>UAS':m.name}</th>`).join('')}</tr></thead><tbody>${[['Total Time',m=>f(m.hours)+' hr'],['Total Cost',m=>money(m.cost)],['Expected pest yield loss · '+mission.state,m=>money(m.expectedLoss)],['Savings vs. yield loss',m=>money(m.saved)]].map(([label,format])=>`<tr><th scope="row">${label}</th>${methods.map(m=>`<td>${format(m)}</td>`).join('')}</tr>`).join('')}</tbody>`;
const definitions=[['Chemical Cost','chemical',false],['Labor Cost','labor',false],['Total Cost','cost',false],['Time','hours',true],['Money Saved','saved',false]];$('graphs').innerHTML=definitions.map(([title,key,isTime])=>`<section class="panel chart"><div class="sectionhead"><h2>${title}</h2><button class="info" data-chart="${key}" aria-label="${title} details">ⓘ</button></div>${chartSvg(title,key,methods,isTime)}</section>`).join('');document.querySelectorAll('[data-chart]').forEach(b=>b.onclick=()=>details('chart',b.dataset.chart));}
function renderEvaluation(s){const e=s.economics,loss=mission.expectedLoss,manual=mission.manual.cost-e.cost,uas=mission.uas.cost-e.cost;
const compare=(value,label)=>value>0?`${money(value)} less than ${label}`:value<0?`${money(-value)} more than ${label}`:`the same as ${label}`;
let verdict,explanation;
if(loss===null){verdict='Add a loss estimate to evaluate the yield-loss margin';explanation='Enter expected pest loss per acre for your state. Operating-cost comparisons are available below.';}
else if(e.saved>0){verdict=`${money(e.saved)} modeled margin against expected yield loss`;explanation=`TG-1 costs ${money(e.cost)} against a ${money(loss)} full-field loss benchmark. Under the spreadsheet’s assumption that treatment prevents that loss, the case has a positive margin of ${money(e.saved)} (${money(e.saved/mission.area)} per acre).`;}
else if(e.saved<0){verdict=`${money(-e.saved)} above the expected yield-loss benchmark`;explanation=`TG-1 costs ${money(e.cost)}, exceeding the ${money(loss)} loss benchmark by ${money(-e.saved)}. Even recovering the full benchmark would not cover the included operating costs in this scenario.`;}
else{verdict='Break-even against the expected yield-loss benchmark';explanation=`TG-1’s ${money(e.cost)} included operating cost equals the expected pest-loss benchmark. There is no modeled margin.`;}
$('evaluationbody').innerHTML=`<h3>${verdict}</h3><p>${explanation}</p><div class="evaluationmetrics"><div><span>Included TG-1 operating cost</span><strong>${money(e.cost)}</strong></div><div><span>Selected scanning + sampling time</span><strong>${f(s.hours)} hr</strong></div></div><p>For <b>${names[selection]}</b> on ${f(mission.area)} soybean acres in ${mission.state}, TG-1’s modeled operating cost is <b>${compare(manual,'manual spraying')}</b> and <b>${compare(uas,'conventional UAS spraying')}</b>.</p><p class="evaluationnote">This is a scenario estimate, not confirmed profit: the state loss benchmark does not establish how much TG-1 could prevent, and the supplied model does not include every ownership or deployment cost.</p><p class="tg1cta">${loss!==null&&e.saved>0?'Your scenario points to a promising fit for the TG-1 concept in targeted soybean pest management. The modeled savings show why this approach is worth developing and testing.':loss!==null?'Your scenario highlights where the TG-1 concept would need to improve to offer a stronger economic case for targeted soybean pest management.':'Your scenario can help explore the potential of the TG-1 concept for targeted soybean pest management. Add an expected loss estimate to assess the economic case.'}</p>`;}
function chartSvg(title,key,methods,isTime){const vals=methods.map(m=>m[key]),ref=key==='cost'?mission.expectedLoss:null,hi=Math.max(0,...vals.map(v=>v??0),ref||0),lo=Math.min(0,...vals.map(v=>v??0)),range=(hi-lo)||1,top=66,bottom=206,y=v=>bottom-(v-lo)/range*(bottom-top),zero=y(0),colors=['#80938b','#44708d','#176b50'],ticks=[hi,(hi+lo)/2,lo],unit=isTime?'hr':'$';const label=v=>v===null?'Enter loss/acre':isTime?f(v):money(v);return `<svg class="bargraph" viewBox="0 0 560 292" role="img" aria-label="${title}: ${methods.map((m,i)=>m.name+' '+label(vals[i])).join(', ')}${ref!==null?'; expected pest yield loss '+money(ref):''}"><title>${title}</title>${ticks.map(v=>`<line x1="90" x2="545" y1="${y(v)}" y2="${y(v)}" stroke="#e0e8e3"/><text x="78" y="${y(v)+4}" text-anchor="end" class="axis">${isTime?f(v):money(v)}</text>`).join('')}<line x1="90" x2="545" y1="${zero}" y2="${zero}" stroke="#96a99d"/>${vals.map((v,i)=>{const x=137+i*145,yy=y(v??0),height=Math.abs(zero-yy);return `<rect class="chartbar" x="${x}" y="${Math.min(zero,yy)}" width="64" height="${height}" rx="3" fill="${colors[i]}"/><text class="barvalue" x="${x+32}" y="${v>=0?yy-9:yy+17}" text-anchor="middle">${label(v)}${isTime?' hr':''}</text><text x="${x+32}" y="254" text-anchor="middle" class="barlabel">${i===1?'<tspan x="'+(x+32)+'" dy="0">Conventional</tspan><tspan x="'+(x+32)+'" dy="26">UAS</tspan>':methods[i].name}</text>`;}).join('')}${ref!==null?`<line class="yield-reference" x1="90" x2="545" y1="${y(ref)}" y2="${y(ref)}" stroke="#a77726" stroke-width="1.5" stroke-dasharray="6 4"/><text x="545" y="23" text-anchor="end" class="referencelabel">Expected yield loss · ${money(ref)}</text>`:''}</svg>`;}
function details(type,key){let title='',body='';const s=active();
if(type==='intro'){title='About this calculator';body='<p>All soybean pests are assumed. Routes apply only to TG-1. Manual and conventional UAS methods treat the full field.</p><p>Scanning and sampling extend the existing Time Calculations.xlsx mission. New cost logic comes only from NASA Project Management.xlsx, Business-Case Spray Cost and Be!A1:D21.</p>';}
if(type==='evaluation'){title='How to interpret the evaluation';body='<p>Modeled margin = full-field expected pest yield loss minus TG-1 chemical and labor cost. Cost savings versus another method = that method’s modeled operating cost minus TG-1’s cost. A positive margin is conditional on preventing the benchmark loss; treatment effectiveness has not been measured.</p><p>Break-even recovery = TG-1 included operating cost ÷ expected loss × 100%. A value above 100% means preventing the entire benchmark loss would still not cover cost. A zero or missing loss rate has no percentage calculation.</p><p>The model includes the selected scanning and sampling mission’s labor plus pesticide cost for damaged acreage. It does not establish spraying-flight time, equipment purchase, depreciation, maintenance, energy, insurance, or a service price. The state estimates reflect historical residual loss under existing management and do not predict untreated loss or TG-1 efficacy.</p>';}
if(type==='feedback'){title='Your feedback';body='<p>Comments and thumbs-up/down reactions are saved in this browser’s local storage. They are not uploaded, shared across devices, or sent to the project team. Clearing browser data removes them. Each saved comment includes a snapshot of your selected scenario when available.</p>';}
if(type==='inputs'){title='Mission assumptions';body='<p>The square field is divided into cells approximately 0.1 mile wide, matching the benchmark’s 0.1-mile squares. A 160-acre field has five rows and five columns. Larger fields have more cells.</p><p>One sample is assigned to each damaged cell. Sample count is the rounded damaged percentage of all cells, with at least one sample for nonzero damage. Spray acreage uses the entered damaged percentage exactly.</p><p>Clustered creates a connected region; Random selects cells without replacement; Scattered distributes locations across the grid. Reshuffle changes only Clustered or Random placement.</p><p>Ground-control distance: 0–9 miles. Flight speed: above 0 and up to 45 mph. Each sample takes 40 seconds. Nonempty missions include 15 minutes for setup, module switching and post-mission work.</p>';}
if(type==='routes'){title='Automatic scan, then sampling';body='<p>Every strategy starts with the same automatic scan, beginning at the bottom right and sweeping row by row. Scanning stops at the final generated damaged location, then returns directly to ground control.</p><p><b>One sample at a time:</b> a separate flight to each detected coordinate and back, via the nearest field point.</p><p><b>One flight/no optimization:</b> one full-field survey flight, collecting the detected samples along its path.</p><p><b>TG-1 optimized:</b> a nearest-neighbor route with limited improvement passes, connecting the same detected coordinates in one flight. This is a calculated heuristic, not a guaranteed global shortest route.</p><p>Scan and sampling travel distance is calculated from the coordinates, including the row-end clearance. The chosen strategy uses the calculated flight time, sampling time and logistics.</p>';}
if(type==='visual'){title='Field & flight details';body='<p>The actual TG-1 top view is extracted from your retained presentation. Launch and return are at the bottom right. Row changes clear the field edge. The scanner returns directly after finding every generated damaged location.</p><p>Amber cells appear as the scanner detects their sample locations. All sampling strategies use those same coordinates. Grid spacing is uniform; ground-control spacing and animation speed are schematic.</p>';if(mission)body+=`<table><tbody>${row('Field grid',mission.n+' × '+mission.n)}${row('Sample locations',mission.count)}${row('Square field side',f(mission.side)+' mi')}${row('Scan distance',f(mission.scanMiles)+' mi')}${row('Scan flight time',f(mission.scanMinutes)+' min')}${row('Actual spray area',f(mission.areaSpray)+' acres')}</tbody></table>`;if(s)body+=`<h3>${names[selection]}</h3><table><tbody>${row('Scanning flight',f(s.scanMinutes)+' min')}${row('Sampling flight',f(s.sampleFlight)+' min')}${row('Taking samples',f(s.sampling)+' min')}${row('Logistics',f(s.logistics)+' min')}${row('Total mission time',f(s.operation)+' min / '+f(s.hours)+' hr')}${row('Fixed TG-1 crew','3 people')}</tbody></table>`;}
if(type==='costs'||type==='chart'){title=type==='chart'?({'chemical':'Chemical Cost','labor':'Labor Cost','cost':'Total Cost','hours':'Time','saved':'Money Saved'}[key]+' details'):'Cost calculation details';body='<p>Editable costs and work rates correspond to yellow inputs in the big bordered table A1:D21 of NASA Project Management.xlsx. Field area is shared; manual and conventional UAS treat the full field, and TG-1 treats the entered damaged percentage.</p><p>Manual time = acres ÷ (workers × acres/hour per worker). UAS time = acres ÷ spraying rate. Their labor cost uses billable hours rounded up to the next whole hour. Chemical cost = sprayed acres × the method’s pesticide cost per acre.</p><p>TG-1 crew stays fixed at three. Its $120/hour combined team rate comes from the spreadsheet and is not multiplied by three again. Actual scanning + sampling hours, including collection and logistics, replace the 0.75-hour placeholder. Billable hours are rounded up to the next whole hour; displayed mission time remains actual time.</p><p><b>State loss rates:</b> Latest available annual estimates for all soybean invertebrate pests from the <a href="https://cropprotectionnetwork.org/yield-loss-calculator/soybean-invertebrate-pests" target="_blank" rel="noopener">Crop Protection Network dataset</a>, retrieved October 6, 2026. Twenty states have 2025 data; Kentucky uses 2024, Wisconsin 2023, Minnesota 2021, and Indiana 2017. Older estimates are labeled beside the input. Other states need a manual rate. Selecting a state loads its estimate; editing the loss field overrides it until another state is chosen.</p><p>These are historical expert estimates of residual yield loss, not pesticide costs or guaranteed avoidable losses. Values are nominal dollars per planted acre, without inflation adjustment. The estimate covers invertebrate pests; it does not add separate disease-loss estimates.</p><p>Expected pest loss = full field acres × selected loss/acre, without multiplying by damage percentage. Savings vs. yield loss / Money Saved = expected loss − total cost. Negative savings mean costs exceed the benchmark. Missing rates leave loss and savings unavailable.</p><p>The dashed horizontal line marks expected yield loss on Total Cost only. Chemical Cost, Labor Cost, Time, and Money Saved have no yield-loss reference line.</p>';if(mission){const d=TG1_LOSS_DATA.states[mission.state];body+=`<p><b>${mission.state}:</b> ${money(mission.rate.lossPerAcre)}/acre${d?` · published ${d.year} estimate $${f(d.lossPerAcre)}/acre`:" · user-entered rate required"}.</p>`};if(s)body+=`<table><tbody>${row('TG-1 mission time replacing D10',f(s.hours)+' hr')}${row('TG-1 labor',money(s.economics.labor))}${row('TG-1 billable labor time',Math.ceil(s.hours)+' hr')}${row('TG-1 chemicals',money(s.economics.chemical))}${row('TG-1 total cost',money(s.economics.cost))}</tbody></table>`;}
if(type==='costs'||type==='chart'||type==='evaluation')body+='<div class="formula-details"><p>Manual actual hours = field acres ÷ (workers × acres/hour per worker)</p><p>UAS actual hours = field acres ÷ spraying acres/hour</p><p>TG-1 actual hours = (scan minutes + sampling-flight minutes + collection minutes + logistics minutes) ÷ 60</p><p>Billable hours = actual hours rounded up to the next whole hour</p><p>Manual / UAS labor cost = billable hours × workers × hourly wage</p><p>TG-1 labor cost = billable hours × $120 combined team rate</p><p>Chemical cost = sprayed acres × pesticide cost/acre</p><p>Total cost = chemical cost + labor cost</p><p>Expected pest yield loss = field acres × selected loss/acre</p><p>Modeled margin = expected pest yield loss − TG-1 total cost</p><p>Savings versus another method = other method total cost − TG-1 total cost</p></div>';
body=body.replace(/Manual time = acres ÷ \(workers × acres\/hour per worker\)\. UAS time = acres ÷ spraying rate\./g,'Manual and UAS work time follows the entered field area, worker counts, and work rates.').replace('Chemical cost = sprayed acres × the method’s pesticide cost per acre.','Chemical costs follow each method’s sprayed acreage and pesticide rate.').replace('Expected pest loss = full field acres × selected loss/acre, without multiplying by damage percentage. Savings vs. yield loss / Money Saved = expected loss − total cost.','Expected pest loss uses the full field without multiplying by damage percentage. Money Saved subtracts total cost from that loss benchmark.').replace('Modeled margin = full-field expected pest yield loss minus TG-1 chemical and labor cost. Cost savings versus another method = that method’s modeled operating cost minus TG-1’s cost.','The evaluation compares the full-field loss benchmark and each method’s included operating costs.');
$('detailtitle').textContent=title;$('detailbody').innerHTML=body;if(!$('details').open)$('details').showModal();}
document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>details(b.dataset.info));$('close').onclick=()=>$('details').close();$('details').addEventListener('click',e=>{if(e.target===$('details')){const r=$('details').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('details').close();}});
lossNote();update();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_tg1_mission',title:'Configure TG-1 mission',description:'Set field and damage inputs, run the automatic scan, and optionally queue a sampling strategy.',inputSchema:{type:'object',properties:{area:{type:'number',exclusiveMinimum:0},damage:{type:'number',minimum:0,maximum:100},distance:{type:'number',minimum:0,maximum:9},speed:{type:'number',exclusiveMinimum:0,maximum:45},distribution:{type:'string',enum:['Clustered','Random','Scattered']},state:{type:'string',enum:states},route:{type:'integer',minimum:0,maximum:2}},required:['area','damage','distance','speed','distribution','state'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){TG1.plan({...input,seed});if(input.route!==undefined&&![0,1,2].includes(input.route))throw new Error('Invalid sampling strategy');['area','damage','distance','speed','distribution','state'].forEach(id=>$(id).value=input[id]);$('lossPerAcre').value=TG1_LOSS_DATA.states[input.state]?.lossPerAcre??'';lossNote();update();if(input.route!==undefined)document.querySelector(`[data-route="${input.route}"]`).click();return {sampleCount:mission.count,scanMinutes:mission.scanMinutes,coordinates:mission.detected.map(c=>({row:c.row,column:c.col})),scenarios:mission.scenarios.map(s=>({missionHours:s.hours,totalCost:s.economics.cost}))};}})).catch(()=>{});}catch{}}


$('reviewscenario').onclick=()=>{$('area').scrollIntoView({behavior:'smooth',block:'center'});$('area').focus({preventScroll:true});};
let reaction=null,feedback=[];const feedbackKey='tg1-calculator-feedback-v1';try{const stored=JSON.parse(localStorage.getItem(feedbackKey)||'[]');if(Array.isArray(stored))feedback=stored.filter(x=>x&&typeof x.comment==='string'&&['up','down',null].includes(x.reaction)).slice(-100);}catch{}
function setReaction(value){reaction=reaction===value?null:value;['up','down'].forEach(v=>$('thumb'+v).setAttribute('aria-pressed',String(reaction===v)));}
$('thumbup').onclick=()=>setReaction('up');$('thumbdown').onclick=()=>setReaction('down');
function showFeedback(){$('savedfeedback').replaceChildren();for(const item of feedback.slice().reverse()){const article=document.createElement('article');article.className='savedcomment';const header=document.createElement('p');header.className='meta';header.textContent=(item.reaction==='up'?'👍 Helpful':item.reaction==='down'?'👎 Needs work':'Comment')+(item.date?' · '+new Date(item.date).toLocaleDateString():'');const text=document.createElement('p');text.textContent=item.comment;article.append(header,text);if(typeof item.scenario==='string'){const context=document.createElement('p');context.className='meta';context.textContent=item.scenario;article.append(context);}$('savedfeedback').append(article);}}
$('feedbackform').onsubmit=e=>{e.preventDefault();const comment=$('comment').value.trim();if(!comment&&!reaction){$('feedbackstatus').textContent='Add a comment or select a reaction first.';return;}const item={comment:comment.slice(0,2000),reaction,date:new Date().toISOString(),scenario:active()?`${mission.state} · ${f(mission.area)} acres · ${names[selection]}`:null};const next=[...feedback,item].slice(-100);try{localStorage.setItem(feedbackKey,JSON.stringify(next));feedback=next;showFeedback();$('comment').value='';reaction=null;['up','down'].forEach(v=>$('thumb'+v).setAttribute('aria-pressed','false'));$('feedbackstatus').textContent='Feedback saved in this browser.';}catch{$('feedbackstatus').textContent='Browser storage is unavailable. Your comment has not been saved; copy it before leaving.';}};showFeedback();
