window.FieldView=(()=>{
 let frame=null,paused=false,path=null,drone=null,arrow=null,trace=null,length=0,progress=0,last=0,duration=12000,onComplete=null,finished=false,milestones=[],scene=null;
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const droneArt=`<g class="dronebody" transform="rotate(-90)"><svg x="-27" y="-22" width="54" height="44" viewBox="410 41 546 447" overflow="hidden"><image class="tg1-top-view" href="drone-top.png" x="0" y="0" width="1366" height="530"/></svg></g>`;
 const project=p=>p.type==='ground'?{x:448,y:380}:{x:60+p.x*300,y:40+p.y*300};
 function routeD(nodes){if(!nodes.length)return '';const points=nodes.map(project);let d='M'+points[0].x+' '+points[0].y;for(let i=1;i<points.length-1;i++){const a=points[i-1],b=points[i],c=points[i+1];if(nodes[i].type!=='turn'){d+=` L${b.x} ${b.y}`;continue;}const incoming=Math.hypot(b.x-a.x,b.y-a.y),outgoing=Math.hypot(c.x-b.x,c.y-b.y),r=Math.min(10,incoming/3,outgoing/3);if(!r){d+=` L${b.x} ${b.y}`;continue;}const p={x:b.x+(a.x-b.x)*r/incoming,y:b.y+(a.y-b.y)*r/incoming},q={x:b.x+(c.x-b.x)*r/outgoing,y:b.y+(c.y-b.y)*r/outgoing};d+=` L${p.x} ${p.y} Q${b.x} ${b.y} ${q.x} ${q.y}`;}const end=points[points.length-1];return d+` L${end.x} ${end.y}`;}
 function reveal(t){if(scene.phase!=='scan')return;for(const m of milestones)if(m.at<=t){document.getElementById('cell-'+m.id)?.classList.add('detected');document.getElementById('sample-'+m.id)?.classList.add('detected');}}
 function drawAt(distance){if(!path)return;const p=path.getPointAtLength(Math.min(length,distance)),q=path.getPointAtLength(Math.min(length,distance+1)),prev=path.getPointAtLength(Math.max(0,distance-1)),angle=Math.atan2(q.y-prev.y,q.x-prev.x)*180/Math.PI;drone.setAttribute('transform',`translate(${p.x} ${p.y}) rotate(${angle})`);const lead=path.getPointAtLength(Math.min(length,distance+28)),end=path.getPointAtLength(Math.min(length,distance+29));arrow.setAttribute('transform',`translate(${lead.x} ${lead.y}) rotate(${Math.atan2(end.y-lead.y,end.x-lead.x)*180/Math.PI})`);trace.style.strokeDashoffset=String(length-distance);reveal(length?distance/length:1);}
 function tick(now){frame=null;if(!path||finished)return;if(!last)last=now;const elapsed=now-last;last=now;if(!paused&&!document.hidden){progress=Math.min(1,progress+elapsed/duration);drawAt(progress*length);if(progress>=1){finished=true;syncButton();const done=onComplete;onComplete=null;done?.();return;}}frame=requestAnimationFrame(tick);}
 function syncButton(){const b=document.getElementById('motiontoggle');b.textContent=finished?'Replay':paused?'Play':'Pause';b.setAttribute('aria-label',finished?'Replay route animation':paused?'Play route animation':'Pause route animation');b.hidden=!path;}
 function render({mission,phase='idle',selection=null,complete}){if(frame!==null)cancelAnimationFrame(frame);frame=null;path=null;progress=0;last=0;finished=false;paused=false;onComplete=complete;scene={phase};milestones=[];
 const active=mission&&(phase==='scan'||phase==='sample'),nodes=active?(phase==='scan'?mission.scanPath:mission.scenarios[selection].path):[],d=routeD(nodes),n=mission?.n||5,damaged=new Set(mission?.damageIds||[]);let cells='';for(let row=0;row<n;row++)for(let col=0;col<n;col++){const id=row*n+col,x=60+col*300/n,y=40+row*300/n,w=300/n,hit=damaged.has(id),known=phase!=='scan';cells+=`<rect id="cell-${id}" class="fieldcell${hit?' damaged':''}${known?' detected':''}" data-row="${row}" data-col="${col}" x="${x}" y="${y}" width="${w}" height="${w}"/>`;if(hit)cells+=`<circle id="sample-${id}" class="samplepoint${known?' detected':''}" cx="${x+w/2}" cy="${y+w/2}" r="${Math.max(1.5,Math.min(4,w/12))}" fill="#a47122"/>`;}
 document.getElementById('fieldview').innerHTML=`<svg class="fieldcanvas" viewBox="0 0 520 440" role="img" aria-label="${n} by ${n} field grid, ${phase==='scan'?'automatic scanning':phase==='sample'?'sampling':'detected locations'} with TG-1 top-view drone"><title>${n} rows and ${n} columns</title><g class="fieldgrid">${cells}</g><rect x="60" y="40" width="300" height="300" fill="none" stroke="#3f795b" stroke-width="1.8"/>${active&&nodes.length>1?`<path class="routebase" d="${d}"/><path class="routetrace" d="${d}"/><g class="flightarrow"><path d="M8 0L-6 -5L-3 0L-6 5Z"/></g>`:''}<circle cx="448" cy="380" r="5" fill="#104436"/><g class="drone" transform="translate(448 380) rotate(-135)">${droneArt}</g><text x="382" y="424">Ground control</text></svg>`;
 if(!active||nodes.length<2){syncButton();if(active)queueMicrotask(()=>onComplete?.());return;}
 path=document.querySelector('.routebase');trace=document.querySelector('.routetrace');drone=document.querySelector('.drone');arrow=document.querySelector('.flightarrow');length=path.getTotalLength();duration=Math.min(16000,Math.max(6500,length/110*1000));trace.style.strokeDasharray=String(length);
 if(phase==='scan'){const pixels=nodes.map(project),cum=[0];for(let i=1;i<pixels.length;i++)cum[i]=cum[i-1]+Math.hypot(pixels[i].x-pixels[i-1].x,pixels[i].y-pixels[i-1].y);milestones=mission.detectedAlong.map(e=>({id:e.id,at:cum[e.pathIndex]/cum[cum.length-1]}));}
 syncButton();drawAt(0);if(reduced.matches){drawAt(length);finished=true;syncButton();queueMicrotask(()=>{const done=onComplete;onComplete=null;done?.();});return;}frame=requestAnimationFrame(tick);
 }
 function toggle(){if(finished){progress=0;finished=false;paused=false;last=0;drawAt(0);frame=requestAnimationFrame(tick);}else{paused=!paused;last=0;}syncButton();}
 return {render,toggle};
})();
